### PR TITLE
bug of NamedGraph annotation fixing

### PR DESCRIPTION
**Pull request by suricatec**
Please can you consider this bug fixing, thanks

### CODE REVIEW

**Comment by mhgrove** [comment]
What issue is this in reference to?

Additionally, where is the corresponding test case?

**Comment by suricatec** [comment]
The problem was that, when you try to modify an entity witch is in a named graph, the persist put it in the default graph. It was because the proxy hide annotations, so I just use the right method to reach it from the bean reflect cache.
But I have not found any test case for this.

**Comment by mhgrove** [comment]
Can you create an issue for this, and amend the PR with a test case that shows that the problem has been fixed?  We can't accept untested code.

**Comment by suricatec** [comment]
ok i'll do that.
sory but it's the first time i do this kind of things !

**Comment by mhgrove** [comment]
No problem, we appreciate the contributions from the community!

**Comment by suricatec** [comment]
i open the issue #98 for it

**Comment by mhgrove** [comment]
Thanks for opening the issue.  When you finish writing test cases, I can merge the PR

**Comment by suricatec** [comment]
Another useful feature may be to allow qname usage in this annotation, because it’s not possible for the moment, only URIs can be used.
It can be easily do in the getNamedGraph method in the EmpireUtil class, just one line must be changed :
return URI.create(aAnnotation.value());
change to :
return URI.create(PrefixMapping.GLOBAL.uri(aAnnotation.value()));

**Pull request closed without merging**
